spring:
  application:
    name: easylearn-user
  data:
    mongodb:
      database: user
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
          enabled: true