spring:
  application:
    name: easylearn-user
  data:
    mongodb:
      database: user
      host: ${EASYLEARN_BD_HOST:userdb}

easylearn:
  isTest: ${EASYLEARN_TEST:false}

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true
